### ISSUE TITLE
对于论文主实验结果的一些疑惑问题

### ISSUE THREAD

**Issue by CDkeeper** [yuezih/less-is-more#1]
您好，最近我们在跟踪一些多模态大模型幻觉领域的前沿工作。
在复现您的工作时，我们发现实验结果与我们复现的结果有较大出入。
在确定输入数据一致、模型一致、采用贪婪搜索解码以及使用您提供的评测代码条件下，我们认为实验结果应该是几乎完全一致的，或者不应该有较大出入。
我们目前针对于论文中Table 1 做出以下复现：
—LLaVA-1.5 (7b)
—LLaVA-1.5(7b） (w/Inst.)
—LLaVA-1.5(7b)  (w/Cap.)

以下是论文与复现结果的对比。
![复现结果](https://github.com/yuezih/less-is-more/assets/92215748/ae40d535-aaa6-4bee-b7d0-31a7204c0435)
以下是复现生成的三个answer文件，分别为基准模型，inst以及cap。
[复现结果文件.zip](https://github.com/yuezih/less-is-more/files/14884998/default.zip)

请问，您能够提供一些帮助使得我们能更好的复现出您的结果吗？

**Comment by yuezih** [comment]
您好，感谢关注我们的工作。

我测试了您的结果，确实与论文中不同。按照您的实验设定，生成结果应该与我们的完全一致才对。目前尚不清楚是什么原因导致，或许我们可以微信沟通一下，看看问题出在哪里。我的微信是`yzihaao`。

我也提供一下我的结果：[official_results.zip](https://github.com/yuezih/less-is-more/files/14885395/official_results.zip)，供参考。
