### ISSUE TITLE
Scripts for the saliency score analysis

### ISSUE THREAD

**Issue by lijm48** [yuezih/less-is-more#2]
Hi! Thanks for your great job!  Could you share the scripts for the saliency score analysis?

**Comment by yuezih** [comment]
Thanks for your interest!

Our saliency score analysis follows [lancopku/label-words-are-anchors](https://github.com/lancopku/label-words-are-anchors). I would strongly recommend you refer to that repo.

The general procedure of saliency analysis:
1. Inserted attention adapters into LLaVA attention blocks for recording gradients during backward.
2. Forward, calculate the loss at your target positions (e.g. the position of EOS tokens), and backward.
3. Obtain the gradients, i.e., the partial derivative of the loss with respect to the attention matrix, which is also a matrix. Averaging them over all attention heads. This matrix is the saliency matrix, where $S_{i,j}$ indicates the saliency score of the $j$-th token to the $i$-th token.
4. Save the saliency matrix and other information like sequence indexes (e.g., the EOS indexes) for offline analysis.

The mentioned repo provides well-organized scripts for saliency analysis; I hope it helps you.  
Feel free to ask if you have further inquires :)

**Comment by lijm48** [comment]
I have got it. Thanks!
