### ISSUE TITLE
Some questions about what model to use.

### ISSUE THREAD

**Issue by 0x4e8** [yuezih/less-is-more#5]
This is a very meaningful work.
I have a question: In the file "CHAIR-eval/eval.sh", does the parameter "MODEL_NAME" represent LoRA weights, such as "yuezih/llava-v1.5-7b-selective-23k-lora", and does the parameter "MODEL_BASE" represent "liuhaotian/llava-v1.5-7b"?

![image](https://github.com/user-attachments/assets/21fb4b9e-c0b6-48eb-833f-8834904467f3)

**Comment by yuezih** [comment]
Yes :)
