### ISSUE TITLE
 Could you please tell me which file the core code of this work is in?

### ISSUE THREAD

**Issue by 0x4e8** [yuezih/less-is-more#6]
This is a great work. Could you please tell me which file the core code of this work is in? Thanks！

**Comment by yuezih** [comment]
Selective EOS Supervision: [llava_llama.py](https://github.com/yuezih/less-is-more/blob/78c6109fdd882ebecd4fc6f80b455d19552477c0/LLaVA/llava/model/language_model/llava_llama.py#L110C9-L110C36)
Scoring EOS Supervision: [llava_llama_filter.py](https://github.com/yuezih/less-is-more/blob/78c6109fdd882ebecd4fc6f80b455d19552477c0/LLaVA/llava/model/language_model/llava_llama_filter.py#L129)

**Comment by 0x4e8** [comment]
Thanks for your answer. I have another question: When I evaluate the dataset, do I need to change the "origin" to 1 (in the original code, "origin" is 0)?
![7f1dace90a110073a33f7ff339bf9da7](https://github.com/user-attachments/assets/b6f3e8a3-2dd2-4420-bf78-352ed2add75f)

**Comment by yuezih** [comment]
Yes. During inference, we need to skip the code that modifies loss calculation and use the original LLaVA code. Sorry for the confusion.
