### ISSUE TITLE
找不到过滤后的数据

### ISSUE THREAD

**Issue by guyuisland** [yuezih/less-is-more#7]
你好，你们的“LLaVA/playground/data/llava_instruction_150k_filtered.json”路径下的数据不存在，找不到过滤后的数据

**Comment by yuezih** [comment]
Sorry可能没上传成功，我马上处理一下

**Comment by yuezih** [comment]
感谢指正！文件太大了，我放到 onedrive 了，请见 [Filtered Data](https://github.com/yuezih/less-is-more/blob/main/README.md#filtered-data)
